/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ProcessInputSection: typeof import('./src/components/process/ProcessInputSection.vue')['default']
    ProcessModeSection: typeof import('./src/components/process/ProcessModeSection.vue')['default']
    ProcessOutputSection: typeof import('./src/components/process/ProcessOutputSection.vue')['default']
    ProcessParameterField: typeof import('./src/components/process/ProcessParameterField.vue')['default']
    ProcessParametersSection: typeof import('./src/components/process/ProcessParametersSection.vue')['default']
    ProcessResultsSection: typeof import('./src/components/process/ProcessResultsSection.vue')['default']
    ProcessRunSection: typeof import('./src/components/process/ProcessRunSection.vue')['default']
    ProcessView: typeof import('./src/components/ProcessView.vue')['default']
    QueueBar: typeof import('./src/components/QueueBar.vue')['default']
    RecipesView: typeof import('./src/components/RecipesView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  }
}
